#!/usr/bin/env python3
"""
Brain MRI version of the bio-inspired evidence-robust classification framework.

Dataset
-------
Designed for the Kaggle "Brain Tumor MRI Dataset" layout:

DATA_ROOT/
    Training/
        glioma/
        meningioma/
        notumor/
        pituitary/
    Testing/
        glioma/
        meningioma/
        notumor/
        pituitary/

The dataset itself does NOT provide brain-region masks. For the proposed method,
provide a separate MASK_ROOT with the same split/class/file layout:

MASK_ROOT/
    Training/
        glioma/
        meningioma/
        notumor/
        pituitary/
    Testing/
        glioma/
        meningioma/
        notumor/
        pituitary/

Each mask must be binary (brain region = white/1, non-brain = black/0) and must
have the same filename stem as its MRI image. Example:
    Training/glioma/Tr-gl_001.jpg
    masks/Training/glioma/Tr-gl_001.png

Training objective
------------------
Baseline:
    L = L_cls

Proposed:
    L = L_cls
        + lambda_cam * L_cam
        + lambda_confidence * L_confidence
        + lambda_dominance * L_dominance

1) L_cls:
   sparse categorical cross-entropy on the original MRI.

2) L_cam:
   CAM-based attention correction. Penalizes samples for which mean CAM
   activation outside the brain region exceeds mean activation inside it.

3) L_confidence:
   Three evidence-reduced inputs are created from the brain-masked image:
      - texture reduction: Gaussian blur (default 11 x 11)
      - shape disruption: 4 x 4 tile shuffle
      - intensity reduction: multiply brain pixels by 0.5
   For each perturbation, a target-class logit increase relative to the original
   image is penalized:
      relu(z_perturbed - z_original).

4) L_dominance:
   Uses the SAME three perturbed logits. The three target-logit drops are:
      d_k = z_original - z_k.
   Their within-sample variance is minimized to discourage dependence on a
   single evidence type.

At final inference, only the original MRI is required. No mask, perturbation,
or extra model is needed by the exported classifier.

Important research note
-----------------------
Masks generated by a heuristic, by manual editing, or by another algorithm
should not be described as "ground-truth" unless they are genuinely verified
ground-truth annotations.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import os
import random
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Sequence, Tuple

import cv2
import numpy as np
import tensorflow as tf
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    f1_score,
    precision_recall_fscore_support,
)
from sklearn.model_selection import train_test_split


# Kaggle folder names, in a fixed order.
DEFAULT_CLASSES = ("glioma", "meningioma", "pituitary", "notumor")
DISPLAY_NAMES = {
    "glioma": "Glioma",
    "meningioma": "Meningioma",
    "pituitary": "Pituitary",
    "notumor": "No Tumor",
}
IMAGE_EXTENSIONS = {".png", ".jpg", ".jpeg", ".bmp", ".tif", ".tiff"}


@dataclass(frozen=True)
class Sample:
    image_path: str
    mask_path: str
    label: int


@dataclass
class LossWeights:
    cam: float = 1.0
    confidence: float = 1.0
    dominance: float = 0.5


def set_global_seed(seed: int) -> None:
    os.environ["PYTHONHASHSEED"] = str(seed)
    random.seed(seed)
    np.random.seed(seed)
    tf.random.set_seed(seed)


def configure_gpu_memory_growth() -> None:
    for gpu in tf.config.list_physical_devices("GPU"):
        try:
            tf.config.experimental.set_memory_growth(gpu, True)
        except RuntimeError:
            pass


def normalize_name(value: str) -> str:
    return "".join(ch.lower() for ch in value if ch.isalnum())


def resolve_split_dir(root: Path, split_name: str) -> Path:
    """
    Accepts common capitalization variants such as Training/training/train.
    """
    aliases = {
        "Training": ("Training", "training", "train"),
        "Testing": ("Testing", "testing", "test"),
    }[split_name]

    for alias in aliases:
        candidate = root / alias
        if candidate.is_dir():
            return candidate

    normalized = {normalize_name(a) for a in aliases}
    matches = [
        p for p in root.iterdir()
        if p.is_dir() and normalize_name(p.name) in normalized
    ]
    if len(matches) == 1:
        return matches[0]
    raise FileNotFoundError(
        f"Could not find {split_name} directory under {root}. "
        f"Expected one of: {aliases}"
    )


def resolve_class_dir(split_dir: Path, class_name: str) -> Path:
    direct = split_dir / class_name
    if direct.is_dir():
        return direct

    wanted = normalize_name(class_name)
    matches = [
        p for p in split_dir.iterdir()
        if p.is_dir() and normalize_name(p.name) == wanted
    ]
    if len(matches) == 1:
        return matches[0]
    raise FileNotFoundError(
        f"Could not find class folder '{class_name}' under {split_dir}."
    )


def list_images(directory: Path) -> List[Path]:
    return sorted(
        p for p in directory.iterdir()
        if p.is_file() and p.suffix.lower() in IMAGE_EXTENSIONS
    )


def canonical_stem(path: Path) -> str:
    stem = path.stem.lower()
    for suffix in ("_mask", "-mask", " mask"):
        if stem.endswith(suffix):
            stem = stem[:-len(suffix)]
    return normalize_name(stem)


def build_mask_index(mask_class_dir: Path) -> Dict[str, Path]:
    if not mask_class_dir.is_dir():
        raise FileNotFoundError(f"Mask class directory not found: {mask_class_dir}")
    return {canonical_stem(p): p for p in list_images(mask_class_dir)}


def collect_split_samples(
    data_split_dir: Path,
    mask_split_dir: Path,
    class_names: Sequence[str],
) -> List[Sample]:
    samples: List[Sample] = []

    for label, class_name in enumerate(class_names):
        image_class_dir = resolve_class_dir(data_split_dir, class_name)
        mask_class_dir = resolve_class_dir(mask_split_dir, class_name)

        image_files = list_images(image_class_dir)
        mask_index = build_mask_index(mask_class_dir)

        missing = []
        for image_path in image_files:
            mask_path = mask_index.get(canonical_stem(image_path))
            if mask_path is None:
                missing.append(image_path.name)
                continue
            samples.append(
                Sample(
                    image_path=str(image_path),
                    mask_path=str(mask_path),
                    label=label,
                )
            )

        if missing:
            raise FileNotFoundError(
                f"{len(missing)} mask(s) missing for class '{class_name}'. "
                f"Examples: {', '.join(missing[:5])}"
            )

    if not samples:
        raise RuntimeError(f"No paired MRI/mask samples found under {data_split_dir}.")
    return samples


def stratified_train_validation_split(
    samples: Sequence[Sample],
    validation_fraction: float,
    seed: int,
) -> Tuple[List[Sample], List[Sample]]:
    labels = np.asarray([s.label for s in samples], dtype=np.int32)
    indices = np.arange(len(samples))

    train_idx, val_idx = train_test_split(
        indices,
        test_size=validation_fraction,
        random_state=seed,
        stratify=labels,
        shuffle=True,
    )
    return [samples[i] for i in train_idx], [samples[i] for i in val_idx]


def decode_image_and_mask(
    image_path: tf.Tensor,
    mask_path: tf.Tensor,
    label: tf.Tensor,
    image_size: int,
) -> Tuple[tf.Tensor, tf.Tensor, tf.Tensor]:
    # MRI -> grayscale float in [0, 1].
    image_bytes = tf.io.read_file(image_path)
    image = tf.io.decode_image(image_bytes, channels=1, expand_animations=False)
    image.set_shape([None, None, 1])
    image = tf.image.convert_image_dtype(image, tf.float32)
    image = tf.image.resize(
        image, [image_size, image_size], method=tf.image.ResizeMethod.BILINEAR
    )
    image = tf.clip_by_value(image, 0.0, 1.0)

    # Binary brain-region mask.
    mask_bytes = tf.io.read_file(mask_path)
    mask = tf.io.decode_image(mask_bytes, channels=1, expand_animations=False)
    mask.set_shape([None, None, 1])
    mask = tf.image.convert_image_dtype(mask, tf.float32)
    mask = tf.image.resize(
        mask, [image_size, image_size], method=tf.image.ResizeMethod.NEAREST_NEIGHBOR
    )
    mask = tf.cast(mask >= 0.5, tf.float32)

    return image, mask, tf.cast(label, tf.int32)


def augment_pair(
    image: tf.Tensor,
    mask: tf.Tensor,
    label: tf.Tensor,
) -> Tuple[tf.Tensor, tf.Tensor, tf.Tensor]:
    """
    Conservative paired augmentation. The same geometric flip is applied to
    image and mask. Brightness acts only on the MRI.
    """
    do_flip = tf.random.uniform([]) > 0.5
    image = tf.cond(do_flip, lambda: tf.image.flip_left_right(image), lambda: image)
    mask = tf.cond(do_flip, lambda: tf.image.flip_left_right(mask), lambda: mask)

    image = tf.image.random_brightness(image, max_delta=0.05)
    image = tf.clip_by_value(image, 0.0, 1.0)
    return image, mask, label


def build_dataset(
    samples: Sequence[Sample],
    image_size: int,
    batch_size: int,
    training: bool,
    seed: int,
    use_augmentation: bool,
) -> tf.data.Dataset:
    image_paths = [s.image_path for s in samples]
    mask_paths = [s.mask_path for s in samples]
    labels = [s.label for s in samples]

    ds = tf.data.Dataset.from_tensor_slices((image_paths, mask_paths, labels))
    if training:
        ds = ds.shuffle(
            buffer_size=max(len(samples), batch_size * 8),
            seed=seed,
            reshuffle_each_iteration=True,
        )

    ds = ds.map(
        lambda p, m, y: decode_image_and_mask(p, m, y, image_size),
        num_parallel_calls=tf.data.AUTOTUNE,
        deterministic=not training,
    )

    if training and use_augmentation:
        ds = ds.map(
            augment_pair,
            num_parallel_calls=tf.data.AUTOTUNE,
            deterministic=False,
        )

    return ds.batch(batch_size, drop_remainder=False).prefetch(tf.data.AUTOTUNE)


def build_backbone(
    name: str,
    rgb_input: tf.Tensor,
    weights: str | None,
) -> tf.keras.Model:
    key = normalize_name(name)

    if key in {"mobilenet", "mobilenetv1"}:
        x = tf.keras.layers.Rescaling(
            scale=2.0, offset=-1.0, name="mobilenet_preprocess"
        )(rgb_input)
        return tf.keras.applications.MobileNet(
            include_top=False,
            weights=weights,
            input_tensor=x,
            alpha=1.0,
        )

    if key in {"efficientnet", "efficientnetb0"}:
        # Keras EfficientNet contains its own 1/255 rescaling and expects [0,255].
        x = tf.keras.layers.Rescaling(255.0, name="efficientnet_preprocess")(rgb_input)
        return tf.keras.applications.EfficientNetB0(
            include_top=False,
            weights=weights,
            input_tensor=x,
        )

    if key in {"densenet", "densenet121"}:
        x = tf.keras.layers.Lambda(
            lambda z: tf.keras.applications.densenet.preprocess_input(z * 255.0),
            name="densenet_preprocess",
        )(rgb_input)
        return tf.keras.applications.DenseNet121(
            include_top=False,
            weights=weights,
            input_tensor=x,
        )

    raise ValueError(
        f"Unsupported backbone '{name}'. "
        "Choose MobileNet-v1, EfficientNet-B0, or DenseNet-121."
    )


def build_models(
    backbone_name: str,
    image_size: int,
    num_classes: int,
    weights: str | None,
    dropout: float,
) -> Tuple[tf.keras.Model, tf.keras.Model, tf.keras.layers.Dense]:
    mri_input = tf.keras.Input(
        shape=(image_size, image_size, 1),
        name="brain_mri",
    )
    rgb = tf.keras.layers.Concatenate(name="gray_to_rgb")(
        [mri_input, mri_input, mri_input]
    )

    backbone = build_backbone(backbone_name, rgb, weights=weights)
    feature_maps = backbone.output
    pooled = tf.keras.layers.GlobalAveragePooling2D(
        name="global_average_pooling"
    )(feature_maps)

    if dropout > 0:
        pooled = tf.keras.layers.Dropout(dropout, name="dropout")(pooled)

    classifier = tf.keras.layers.Dense(
        num_classes,
        activation=None,
        name="classifier_logits",
    )
    logits = classifier(pooled)

    training_model = tf.keras.Model(
        inputs=mri_input,
        outputs=(logits, feature_maps),
        name=f"{normalize_name(backbone_name)}_brain_mri_training",
    )
    inference_model = tf.keras.Model(
        inputs=mri_input,
        outputs=logits,
        name=f"{normalize_name(backbone_name)}_brain_mri_classifier",
    )

    return training_model, inference_model, classifier


def gaussian_kernel(size: int, sigma: float) -> tf.Tensor:
    coords = tf.cast(tf.range(size), tf.float32) - (size - 1) / 2.0
    kernel_1d = tf.exp(-(coords ** 2) / (2.0 * sigma ** 2))
    kernel_1d /= tf.reduce_sum(kernel_1d)
    kernel_2d = tf.tensordot(kernel_1d, kernel_1d, axes=0)
    kernel_2d = kernel_2d[:, :, tf.newaxis, tf.newaxis]
    return kernel_2d


def gaussian_blur(images: tf.Tensor, kernel: tf.Tensor) -> tf.Tensor:
    return tf.nn.depthwise_conv2d(
        images,
        kernel,
        strides=[1, 1, 1, 1],
        padding="SAME",
    )


def tile_shuffle(
    images: tf.Tensor,
    grid_size: int,
    image_size: int,
    randomize: bool,
) -> tf.Tensor:
    """
    Shuffle exactly grid_size x grid_size tiles.
    Default grid_size=4 -> 16 tiles.
    """
    padded_size = int(math.ceil(image_size / grid_size) * grid_size)
    tile_size = padded_size // grid_size

    pad_bottom = padded_size - image_size
    pad_right = padded_size - image_size
    padded = tf.pad(images, [[0, 0], [0, pad_bottom], [0, pad_right], [0, 0]])

    batch = tf.shape(padded)[0]
    channels = tf.shape(padded)[-1]

    tiles = tf.reshape(
        padded,
        [batch, grid_size, tile_size, grid_size, tile_size, channels],
    )
    tiles = tf.transpose(tiles, [0, 1, 3, 2, 4, 5])
    tiles = tf.reshape(
        tiles,
        [batch, grid_size * grid_size, tile_size, tile_size, channels],
    )

    if randomize:
        def shuffle_one(sample_tiles: tf.Tensor) -> tf.Tensor:
            perm = tf.random.shuffle(tf.range(grid_size * grid_size))
            return tf.gather(sample_tiles, perm)

        shuffled = tf.map_fn(
            shuffle_one,
            tiles,
            fn_output_signature=tf.TensorSpec(
                shape=(grid_size * grid_size, tile_size, tile_size, 1),
                dtype=tf.float32,
            ),
        )
    else:
        # Deterministic permutation for validation/testing.
        n = grid_size * grid_size
        order = []
        left, right = 0, n - 1
        while left <= right:
            order.append(right)
            if left != right:
                order.append(left)
            left += 1
            right -= 1
        shuffled = tf.gather(
            tiles,
            tf.constant(order, dtype=tf.int32),
            axis=1,
        )

    shuffled = tf.reshape(
        shuffled,
        [batch, grid_size, grid_size, tile_size, tile_size, channels],
    )
    shuffled = tf.transpose(shuffled, [0, 1, 3, 2, 4, 5])
    shuffled = tf.reshape(
        shuffled,
        [batch, padded_size, padded_size, channels],
    )
    return shuffled[:, :image_size, :image_size, :]


def target_logits(logits: tf.Tensor, labels: tf.Tensor) -> tf.Tensor:
    return tf.gather(logits, labels, axis=1, batch_dims=1)


def normalized_target_cam(
    feature_maps: tf.Tensor,
    labels: tf.Tensor,
    classifier_layer: tf.keras.layers.Dense,
) -> tf.Tensor:
    """
    Classic CAM is available because the classifier follows global average pooling.
    """
    target_weights = tf.transpose(
        tf.gather(classifier_layer.kernel, labels, axis=1)
    )
    cam = tf.einsum("bhwc,bc->bhw", feature_maps, target_weights)
    cam = tf.nn.relu(cam)

    cam_min = tf.reduce_min(cam, axis=[1, 2], keepdims=True)
    cam_max = tf.reduce_max(cam, axis=[1, 2], keepdims=True)
    cam = (cam - cam_min) / (cam_max - cam_min + 1e-7)
    return cam[..., tf.newaxis]


def cam_attention_terms(
    cam: tf.Tensor,
    masks: tf.Tensor,
) -> Tuple[tf.Tensor, tf.Tensor, tf.Tensor]:
    mask_small = tf.image.resize(
        masks,
        tf.shape(cam)[1:3],
        method=tf.image.ResizeMethod.NEAREST_NEIGHBOR,
    )
    mask_small = tf.cast(mask_small >= 0.5, tf.float32)
    outside = 1.0 - mask_small

    inside_attention = tf.reduce_sum(cam * mask_small, axis=[1, 2, 3]) / (
        tf.reduce_sum(mask_small, axis=[1, 2, 3]) + 1e-7
    )
    outside_attention = tf.reduce_sum(cam * outside, axis=[1, 2, 3]) / (
        tf.reduce_sum(outside, axis=[1, 2, 3]) + 1e-7
    )

    # Only penalize pathological cases: outside > inside.
    framing_penalty = tf.nn.relu(outside_attention - inside_attention)
    return inside_attention, outside_attention, framing_penalty


class EvidenceRobustTrainer:
    def __init__(
        self,
        training_model: tf.keras.Model,
        inference_model: tf.keras.Model,
        classifier_layer: tf.keras.layers.Dense,
        optimizer: tf.keras.optimizers.Optimizer,
        loss_weights: LossWeights,
        blur_kernel: tf.Tensor,
        image_size: int,
        tile_grid: int,
        gradient_clip_norm: float,
        method: str,
    ) -> None:
        self.training_model = training_model
        self.inference_model = inference_model
        self.classifier_layer = classifier_layer
        self.optimizer = optimizer
        self.loss_weights = loss_weights
        self.blur_kernel = blur_kernel
        self.image_size = image_size
        self.tile_grid = tile_grid
        self.gradient_clip_norm = gradient_clip_norm
        self.method = method

        self.ce = tf.keras.losses.SparseCategoricalCrossentropy(
            from_logits=True,
            reduction=tf.keras.losses.Reduction.NONE,
        )

    def compute_proposed_losses(
        self,
        images: tf.Tensor,
        masks: tf.Tensor,
        labels: tf.Tensor,
        training: bool,
    ) -> Dict[str, tf.Tensor]:
        original_logits, feature_maps = self.training_model(
            images, training=training
        )
        original_target = target_logits(original_logits, labels)

        classification_loss = tf.reduce_mean(
            self.ce(labels, original_logits)
        )

        # CAM attention correction.
        cam = normalized_target_cam(
            feature_maps,
            labels,
            self.classifier_layer,
        )
        inside_att, outside_att, framing_penalty = cam_attention_terms(
            cam, masks
        )
        cam_loss = tf.reduce_mean(framing_penalty)

        # Evidence reduction is applied to the brain-masked image.
        masked = images * masks

        texture_reduced = gaussian_blur(masked, self.blur_kernel)
        shape_reduced = tile_shuffle(
            masked,
            grid_size=self.tile_grid,
            image_size=self.image_size,
            randomize=training,
        )
        intensity_reduced = 0.5 * masked

        texture_logits = self.inference_model(
            texture_reduced, training=training
        )
        shape_logits = self.inference_model(
            shape_reduced, training=training
        )
        intensity_logits = self.inference_model(
            intensity_reduced, training=training
        )

        texture_target = target_logits(texture_logits, labels)
        shape_target = target_logits(shape_logits, labels)
        intensity_target = target_logits(intensity_logits, labels)

        # Confidence inconsistency:
        # weakening evidence should not INCREASE the target-class logit.
        confidence_terms = tf.stack(
            [
                tf.nn.relu(texture_target - original_target),
                tf.nn.relu(shape_target - original_target),
                tf.nn.relu(intensity_target - original_target),
            ],
            axis=1,
        )
        confidence_loss = tf.reduce_mean(
            tf.reduce_mean(confidence_terms, axis=1)
        )

        # Single-evidence dominance:
        # large disparity among the three logit drops is penalized.
        drops = tf.stack(
            [
                original_target - texture_target,
                original_target - shape_target,
                original_target - intensity_target,
            ],
            axis=1,
        )
        mean_drop = tf.reduce_mean(drops, axis=1, keepdims=True)
        per_sample_dominance = tf.reduce_mean(
            tf.square(drops - mean_drop),
            axis=1,
        )
        dominance_loss = tf.reduce_mean(per_sample_dominance)

        total_loss = (
            classification_loss
            + self.loss_weights.cam * cam_loss
            + self.loss_weights.confidence * confidence_loss
            + self.loss_weights.dominance * dominance_loss
        )

        pred = tf.argmax(original_logits, axis=1, output_type=tf.int32)
        accuracy = tf.reduce_mean(
            tf.cast(pred == labels, tf.float32)
        )

        return {
            "total_loss": total_loss,
            "classification_loss": classification_loss,
            "cam_loss": cam_loss,
            "confidence_loss": confidence_loss,
            "dominance_loss": dominance_loss,
            "accuracy": accuracy,
            "inside_attention": tf.reduce_mean(inside_att),
            "outside_attention": tf.reduce_mean(outside_att),
            "original_logits": original_logits,
            "cam": cam,
            "confidence_terms": confidence_terms,
            "drops": drops,
            "per_sample_framing": framing_penalty,
            "per_sample_dominance": per_sample_dominance,
        }

    def compute_baseline_loss(
        self,
        images: tf.Tensor,
        labels: tf.Tensor,
        training: bool,
    ) -> Dict[str, tf.Tensor]:
        logits = self.inference_model(images, training=training)
        classification_loss = tf.reduce_mean(self.ce(labels, logits))
        pred = tf.argmax(logits, axis=1, output_type=tf.int32)
        accuracy = tf.reduce_mean(tf.cast(pred == labels, tf.float32))
        zero = tf.constant(0.0, dtype=tf.float32)

        return {
            "total_loss": classification_loss,
            "classification_loss": classification_loss,
            "cam_loss": zero,
            "confidence_loss": zero,
            "dominance_loss": zero,
            "accuracy": accuracy,
            "inside_attention": zero,
            "outside_attention": zero,
        }

    @tf.function(reduce_retracing=True)
    def train_step(
        self,
        images: tf.Tensor,
        masks: tf.Tensor,
        labels: tf.Tensor,
    ) -> Dict[str, tf.Tensor]:
        with tf.GradientTape() as tape:
            if self.method == "baseline":
                values = self.compute_baseline_loss(
                    images, labels, training=True
                )
            else:
                values = self.compute_proposed_losses(
                    images, masks, labels, training=True
                )

        grads = tape.gradient(
            values["total_loss"],
            self.training_model.trainable_variables,
        )
        pairs = [
            (g, v) for g, v in zip(
                grads, self.training_model.trainable_variables
            ) if g is not None
        ]

        if self.gradient_clip_norm > 0 and pairs:
            clipped, _ = tf.clip_by_global_norm(
                [g for g, _ in pairs],
                self.gradient_clip_norm,
            )
            pairs = [
                (g, v)
                for g, (_, v) in zip(clipped, pairs)
            ]

        self.optimizer.apply_gradients(pairs)
        return values

    @tf.function(reduce_retracing=True)
    def validation_step(
        self,
        images: tf.Tensor,
        masks: tf.Tensor,
        labels: tf.Tensor,
    ) -> Dict[str, tf.Tensor]:
        if self.method == "baseline":
            return self.compute_baseline_loss(
                images, labels, training=False
            )
        return self.compute_proposed_losses(
            images, masks, labels, training=False
        )

    @tf.function(reduce_retracing=True)
    def behavioral_step(
        self,
        images: tf.Tensor,
        masks: tf.Tensor,
        labels: tf.Tensor,
    ) -> Dict[str, tf.Tensor]:
        # Behavioral metrics are evaluated for BOTH baseline and proposed
        # models with the same brain masks/perturbations.
        return self.compute_proposed_losses(
            images, masks, labels, training=False
        )


def new_running_metrics() -> Dict[str, tf.keras.metrics.Mean]:
    keys = (
        "total_loss",
        "classification_loss",
        "cam_loss",
        "confidence_loss",
        "dominance_loss",
        "accuracy",
        "inside_attention",
        "outside_attention",
    )
    return {k: tf.keras.metrics.Mean(name=k) for k in keys}


def update_running_metrics(
    running: Dict[str, tf.keras.metrics.Mean],
    values: Dict[str, tf.Tensor],
) -> None:
    for key, metric in running.items():
        metric.update_state(values[key])


def metric_results(
    running: Dict[str, tf.keras.metrics.Mean]
) -> Dict[str, float]:
    return {
        key: float(metric.result().numpy())
        for key, metric in running.items()
    }


def append_epoch_log(
    path: Path,
    row: Dict[str, float | int],
) -> None:
    write_header = not path.exists()
    with path.open("a", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=list(row.keys()))
        if write_header:
            writer.writeheader()
        writer.writerow(row)


def train_model(
    trainer: EvidenceRobustTrainer,
    train_ds: tf.data.Dataset,
    val_ds: tf.data.Dataset,
    epochs: int,
    output_dir: Path,
) -> Path:
    log_path = output_dir / "epoch_log.csv"
    if log_path.exists():
        log_path.unlink()

    best_loss = float("inf")
    best_weights = output_dir / "best_model.weights.h5"

    for epoch in range(1, epochs + 1):
        tr = new_running_metrics()
        va = new_running_metrics()

        for images, masks, labels in train_ds:
            values = trainer.train_step(images, masks, labels)
            update_running_metrics(tr, values)

        for images, masks, labels in val_ds:
            values = trainer.validation_step(images, masks, labels)
            update_running_metrics(va, values)

        trv = metric_results(tr)
        vav = metric_results(va)

        row = {"epoch": epoch}
        row.update({f"train_{k}": v for k, v in trv.items()})
        row.update({f"val_{k}": v for k, v in vav.items()})
        append_epoch_log(log_path, row)

        print(
            f"Epoch {epoch:03d}/{epochs:03d} | "
            f"train loss={trv['total_loss']:.5f}, "
            f"acc={trv['accuracy']:.4f} | "
            f"val loss={vav['total_loss']:.5f}, "
            f"acc={vav['accuracy']:.4f}"
        )

        if vav["total_loss"] < best_loss:
            best_loss = vav["total_loss"]
            trainer.inference_model.save_weights(best_weights)

    trainer.inference_model.load_weights(best_weights)

    # Keras-native format is preferred for reproducibility.
    keras_path = output_dir / "brain_mri_classifier.keras"
    trainer.inference_model.save(keras_path, include_optimizer=False)

    # Optional HDF5 copy for compatibility with older workflows.
    h5_path = output_dir / "brain_mri_classifier.h5"
    try:
        trainer.inference_model.save(h5_path, include_optimizer=False)
    except Exception as exc:
        print(f"Warning: HDF5 export skipped: {exc}", file=sys.stderr)

    return best_weights


def save_classification_outputs(
    y_true: np.ndarray,
    y_pred: np.ndarray,
    class_names: Sequence[str],
    output_dir: Path,
) -> float:
    macro_f1 = float(f1_score(y_true, y_pred, average="macro"))

    cm = confusion_matrix(
        y_true,
        y_pred,
        labels=np.arange(len(class_names)),
    )
    np.savetxt(
        output_dir / "confusion_matrix.csv",
        cm,
        delimiter=",",
        fmt="%d",
    )

    precision, recall, f1_values, support = (
        precision_recall_fscore_support(
            y_true,
            y_pred,
            labels=np.arange(len(class_names)),
            zero_division=0,
        )
    )

    with (output_dir / "class_metrics.csv").open(
        "w", newline="", encoding="utf-8"
    ) as f:
        writer = csv.writer(f)
        writer.writerow(["class", "PPV", "TPR", "F1", "support"])
        for i, class_name in enumerate(class_names):
            writer.writerow(
                [
                    DISPLAY_NAMES.get(class_name, class_name),
                    float(precision[i]),
                    float(recall[i]),
                    float(f1_values[i]),
                    int(support[i]),
                ]
            )

    report = classification_report(
        y_true,
        y_pred,
        target_names=[
            DISPLAY_NAMES.get(c, c) for c in class_names
        ],
        zero_division=0,
    )
    (output_dir / "classification_report.txt").write_text(
        report, encoding="utf-8"
    )

    return macro_f1


def cam_to_overlay(
    image_gray: np.ndarray,
    cam: np.ndarray,
    threshold: float,
    alpha_scale: float = 0.62,
) -> np.ndarray:
    """
    Overlay only: the underlying MRI geometry is never regenerated or warped.
    """
    image_u8 = np.clip(
        image_gray * 255.0, 0, 255
    ).astype(np.uint8)
    base = cv2.cvtColor(image_u8, cv2.COLOR_GRAY2BGR)

    cam_u8 = np.clip(cam * 255.0, 0, 255).astype(np.uint8)
    colored = cv2.applyColorMap(
        cam_u8,
        cv2.COLORMAP_JET,
    )

    alpha = np.clip(
        (cam - threshold) / max(1e-7, 1.0 - threshold),
        0.0,
        1.0,
    )
    alpha = (alpha * alpha_scale)[..., np.newaxis]

    overlay = (
        (1.0 - alpha) * base.astype(np.float32)
        + alpha * colored.astype(np.float32)
    )
    return np.clip(overlay, 0, 255).astype(np.uint8)


def evaluate_model(
    trainer: EvidenceRobustTrainer,
    test_ds: tf.data.Dataset,
    class_names: Sequence[str],
    output_dir: Path,
    cam_threshold: float,
    cam_examples: int,
) -> Dict[str, float]:
    y_true_all: List[np.ndarray] = []
    y_pred_all: List[np.ndarray] = []

    framing_all: List[np.ndarray] = []
    confidence_all: List[np.ndarray] = []
    dominance_all: List[np.ndarray] = []

    cam_dir = output_dir / "cam_overlays"
    cam_dir.mkdir(parents=True, exist_ok=True)
    saved = 0

    for images, masks, labels in test_ds:
        values = trainer.behavioral_step(
            images, masks, labels
        )

        logits = values["original_logits"]
        pred = tf.argmax(
            logits,
            axis=1,
            output_type=tf.int32,
        )

        y_true_all.append(labels.numpy())
        y_pred_all.append(pred.numpy())

        framing_all.append(
            values["per_sample_framing"].numpy()
        )
        confidence_all.append(
            tf.reduce_mean(
                values["confidence_terms"], axis=1
            ).numpy()
        )
        dominance_all.append(
            values["per_sample_dominance"].numpy()
        )

        if saved < cam_examples:
            cams = tf.image.resize(
                values["cam"],
                [trainer.image_size, trainer.image_size],
                method=tf.image.ResizeMethod.BILINEAR,
            ).numpy()

            images_np = images.numpy()
            labels_np = labels.numpy()
            pred_np = pred.numpy()

            for i in range(images_np.shape[0]):
                if saved >= cam_examples:
                    break

                original_u8 = np.clip(
                    images_np[i, ..., 0] * 255.0,
                    0,
                    255,
                ).astype(np.uint8)

                overlay = cam_to_overlay(
                    images_np[i, ..., 0],
                    cams[i, ..., 0],
                    threshold=cam_threshold,
                )

                cv2.imwrite(
                    str(cam_dir / f"sample_{saved:03d}_original.png"),
                    original_u8,
                )
                cv2.imwrite(
                    str(cam_dir / f"sample_{saved:03d}_cam.png"),
                    overlay,
                )

                metadata = {
                    "ground_truth": DISPLAY_NAMES.get(
                        class_names[int(labels_np[i])],
                        class_names[int(labels_np[i])],
                    ),
                    "prediction": DISPLAY_NAMES.get(
                        class_names[int(pred_np[i])],
                        class_names[int(pred_np[i])],
                    ),
                    "cam_threshold": cam_threshold,
                }
                (
                    cam_dir / f"sample_{saved:03d}.json"
                ).write_text(
                    json.dumps(metadata, indent=2),
                    encoding="utf-8",
                )
                saved += 1

    y_true = np.concatenate(y_true_all)
    y_pred = np.concatenate(y_pred_all)

    macro_f1 = save_classification_outputs(
        y_true,
        y_pred,
        class_names,
        output_dir,
    )

    metrics = {
        "macro_f1": macro_f1,
        "framing_sensitivity": float(
            np.mean(np.concatenate(framing_all))
        ),
        "confidence_inconsistency": float(
            np.mean(np.concatenate(confidence_all))
        ),
        "single_evidence_dominance": float(
            np.mean(np.concatenate(dominance_all))
        ),
        "num_test_samples": int(y_true.shape[0]),
    }

    (output_dir / "test_metrics.json").write_text(
        json.dumps(metrics, indent=2),
        encoding="utf-8",
    )
    return metrics


def parse_weights(value: str) -> str | None:
    value = value.strip().lower()
    if value in {"none", "null", "random"}:
        return None
    if value == "imagenet":
        return "imagenet"
    raise argparse.ArgumentTypeError(
        "--weights must be 'imagenet' or 'none'."
    )


def parse_classes(value: str) -> Tuple[str, ...]:
    classes = tuple(
        x.strip() for x in value.split(",") if x.strip()
    )
    if len(classes) < 2:
        raise argparse.ArgumentTypeError(
            "Provide at least two comma-separated classes."
        )
    return classes


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description=(
            "Train/evaluate the brain-MRI version of the "
            "evidence-robust framework."
        )
    )

    p.add_argument(
        "--data-root",
        type=Path,
        required=True,
        help="Root containing Training/ and Testing/.",
    )
    p.add_argument(
        "--mask-root",
        type=Path,
        required=True,
        help="Parallel root containing binary brain-region masks.",
    )
    p.add_argument(
        "--output-dir",
        type=Path,
        default=Path("brain_mri_outputs"),
    )

    p.add_argument(
        "--backbone",
        default="DenseNet-121",
        choices=("MobileNet-v1", "EfficientNet-B0", "DenseNet-121"),
    )
    p.add_argument(
        "--method",
        default="proposed",
        choices=("baseline", "proposed"),
    )
    p.add_argument(
        "--classes",
        type=parse_classes,
        default=DEFAULT_CLASSES,
        help="Folder names in class order.",
    )

    p.add_argument(
        "--image-size",
        type=int,
        default=224,
        help="All MRIs and masks are resized to this square size.",
    )
    p.add_argument(
        "--validation-fraction",
        type=float,
        default=0.10,
        help="Stratified fraction split from Kaggle Training set.",
    )
    p.add_argument("--batch-size", type=int, default=4)
    p.add_argument("--epochs", type=int, default=50)
    p.add_argument("--learning-rate", type=float, default=1e-3)

    p.add_argument("--lambda-cam", type=float, default=1.0)
    p.add_argument("--lambda-confidence", type=float, default=1.0)
    p.add_argument("--lambda-dominance", type=float, default=0.5)

    p.add_argument("--blur-kernel", type=int, default=11)
    p.add_argument("--blur-sigma", type=float, default=3.0)
    p.add_argument("--tile-grid", type=int, default=4)
    p.add_argument("--dropout", type=float, default=0.0)
    p.add_argument("--gradient-clip-norm", type=float, default=5.0)
    p.add_argument("--weights", type=parse_weights, default="imagenet")

    p.add_argument("--seed", type=int, default=42)
    p.add_argument(
        "--no-augmentation",
        action="store_true",
        help="Disable conservative train-time augmentation.",
    )

    p.add_argument("--cam-threshold", type=float, default=0.20)
    p.add_argument("--cam-examples", type=int, default=20)

    p.add_argument(
        "--evaluate-only",
        action="store_true",
    )
    p.add_argument(
        "--weights-file",
        type=Path,
        default=None,
        help="best_model.weights.h5 used with --evaluate-only.",
    )
    return p


def validate_args(args: argparse.Namespace) -> None:
    if not args.data_root.is_dir():
        raise FileNotFoundError(
            f"--data-root not found: {args.data_root}"
        )
    if not args.mask_root.is_dir():
        raise FileNotFoundError(
            f"--mask-root not found: {args.mask_root}"
        )
    if not (0.0 < args.validation_fraction < 0.5):
        raise ValueError(
            "--validation-fraction must be between 0 and 0.5."
        )
    if args.blur_kernel <= 0 or args.blur_kernel % 2 == 0:
        raise ValueError(
            "--blur-kernel must be a positive odd integer."
        )
    if args.tile_grid <= 1:
        raise ValueError("--tile-grid must be > 1.")
    if not (0.0 <= args.cam_threshold < 1.0):
        raise ValueError(
            "--cam-threshold must be in [0, 1)."
        )
    if args.evaluate_only and args.weights_file is None:
        raise ValueError(
            "--weights-file is required with --evaluate-only."
        )


def main() -> None:
    args = build_parser().parse_args()
    validate_args(args)

    set_global_seed(args.seed)
    configure_gpu_memory_growth()
    args.output_dir.mkdir(parents=True, exist_ok=True)

    class_names = tuple(args.classes)

    data_training = resolve_split_dir(
        args.data_root, "Training"
    )
    data_testing = resolve_split_dir(
        args.data_root, "Testing"
    )
    mask_training = resolve_split_dir(
        args.mask_root, "Training"
    )
    mask_testing = resolve_split_dir(
        args.mask_root, "Testing"
    )

    all_train_samples = collect_split_samples(
        data_training,
        mask_training,
        class_names,
    )
    test_samples = collect_split_samples(
        data_testing,
        mask_testing,
        class_names,
    )

    train_samples, val_samples = (
        stratified_train_validation_split(
            all_train_samples,
            validation_fraction=args.validation_fraction,
            seed=args.seed,
        )
    )

    print(
        f"Samples: train={len(train_samples)}, "
        f"validation={len(val_samples)}, "
        f"test={len(test_samples)}"
    )

    train_ds = build_dataset(
        train_samples,
        image_size=args.image_size,
        batch_size=args.batch_size,
        training=True,
        seed=args.seed,
        use_augmentation=not args.no_augmentation,
    )
    val_ds = build_dataset(
        val_samples,
        image_size=args.image_size,
        batch_size=args.batch_size,
        training=False,
        seed=args.seed,
        use_augmentation=False,
    )
    test_ds = build_dataset(
        test_samples,
        image_size=args.image_size,
        batch_size=args.batch_size,
        training=False,
        seed=args.seed,
        use_augmentation=False,
    )

    training_model, inference_model, classifier_layer = (
        build_models(
            backbone_name=args.backbone,
            image_size=args.image_size,
            num_classes=len(class_names),
            weights=args.weights,
            dropout=args.dropout,
        )
    )

    optimizer = tf.keras.optimizers.Adam(
        learning_rate=args.learning_rate
    )
    blur_kernel = gaussian_kernel(
        args.blur_kernel,
        args.blur_sigma,
    )

    trainer = EvidenceRobustTrainer(
        training_model=training_model,
        inference_model=inference_model,
        classifier_layer=classifier_layer,
        optimizer=optimizer,
        loss_weights=LossWeights(
            cam=args.lambda_cam,
            confidence=args.lambda_confidence,
            dominance=args.lambda_dominance,
        ),
        blur_kernel=blur_kernel,
        image_size=args.image_size,
        tile_grid=args.tile_grid,
        gradient_clip_norm=args.gradient_clip_norm,
        method=args.method,
    )

    config = vars(args).copy()
    for key in ("data_root", "mask_root", "output_dir", "weights_file"):
        if config.get(key) is not None:
            config[key] = str(config[key])
    config["classes"] = list(class_names)

    (args.output_dir / "configuration.json").write_text(
        json.dumps(config, indent=2),
        encoding="utf-8",
    )

    if args.evaluate_only:
        inference_model.load_weights(args.weights_file)
    else:
        train_model(
            trainer,
            train_ds,
            val_ds,
            epochs=args.epochs,
            output_dir=args.output_dir,
        )

    metrics = evaluate_model(
        trainer,
        test_ds,
        class_names=class_names,
        output_dir=args.output_dir,
        cam_threshold=args.cam_threshold,
        cam_examples=args.cam_examples,
    )

    print("\nTest results")
    for key, value in metrics.items():
        if isinstance(value, float):
            print(f"{key}: {value:.6f}")
        else:
            print(f"{key}: {value}")


if __name__ == "__main__":
    main()
